global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: airflow
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:9102']
        labels:
          airflow_id: 'airflow'
    